Spandan-Bhattacharya/Solve_it

- css/styles.css
Fixes #13 
Changed some css in the nav bar.
> [Fix]: nav bar styling.

- README.md
- html/sudoku_solver_4x4.html
- javascript/sudoku_solver4.js
1) Now when an invalid input is given, a message is displayed inside html of the website itself, without using the "alert" function.
2) The grid gets reset, after the message is shown, thus allowing the user to re-enter the values without refreshing the page.
Both these cases were solved..
> Sudoku-solver-4x4: Invalid input alert. #7

- css/styles.css
- index.html
- javascript/GoToTop.js
Fix issue : #40 
As part of enhancing user experience on our website, we'd like to implement a "Go to Top" button. This button will provide users with a convenient way to quickly scroll to the top of the page, especially on longer pages.
Add Button in HTML: Integrate the "Go to Top" button at the bottom of our web pages.
Update the HTML file to include the button.
Ensure the button is styled appropriately for a clean and user-friendly appearance.
CSS Styling: Apply styles to the button for a visually appealing look.
JavaScript Functionality:
Write JavaScript functions to handle scrolling to the top smoothly.
Display the button dynamically based on the user's scroll position.
Testing:
Test the "Go to Top" button on various browsers to ensure consistent behaviour.
Verify that the button …
> ADD:Add a Go To Top button

- css/styles.css
- index.html
***Fixed button behavior***:
The buttons respond correctly when clicked anywhere within the button-shaped area
> Fix Button Click Issue

- css/searchstyle.css
Updated the css of search bar issue #52 .
> updated the css of search-bar.

- css/styles.css
- html/about.html
**Fixed 2 problems listed in the issue**
> UI Fix: #55

- javascript/autocomplete.js
1. Clicking outside the *search-box* & *result-box* closes the ***result box***.
2. Again clicking inside the *search-box* re-opens the suggestions with previous suggestions list.
> search bar fix

- index.html
Closes issue #80 
Adds Social Accounts
- All social accounts of the developer are now attested through the website
Tested on my local system and it works fine
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor
Attaching video to show that now links are finely working and ready to get merged with the main project.
> Social links are added

- css_files/styles.css
- html_files/about.html
- html_files/contact.html
- index.html
I have redesigned the button, also previously contact and about page was not linked with this button, i have linked that too.
Thank you.
> Redesigned the Gototop button

- css_files/sudoku_solver6.css
- html_files/sudoku_solver_6x6.html
- index.html
- javascript/sudoku_solver6.js
Closes #95 
Users will now be able to solve 6x6 sudoku game.
> Implemented 6x6 Sudoku Solver

- css_files/styles.css
- index.html
The icon of the go to top button is now visible.
Fixes #104 
@Spandan-Bhattacharya please go through the changes and review them.
> UI: Go To Top Button Fixed

- css_files/styles.css
- html_files/contact.html
I have made the mentioned changes and set the navbar back to its original size and took care that the image does not look a bit stretched in contact us page.
Resovled issue #76
> Logo on navbar 

- css_files/styles.css
- html_files/contact.html
Made changes in the HTML and CSS codes of the contact us page and finally it looks like this:
@Spandan-Bhattacharya
> Redesigned the contact us page by updating HTML and CSS files.

- .vscode/settings.json
- css_files/searchstyle.css
- css_files/styles.css
- html_files/contact.html
- index.html
- javascript/script.js
i have added hamburger section in home and contact page, i have made is responsive. I have made changes in, 
i ) index.html file
ii ) contact.html file 
iii ) style.css
iv ) searchStyle.css
> hamburger section

- css_files/styles.css
- html_files/about.html
- html_files/contact.html
- index.html
Improved the Footer of the Original Website.  I am attaching the Screenshot below. Issue No = **#100**
> Improved Footer of the Website.

- css_files/sudoku_solver6.css
- html_files/sudoku_solver_6x6.html
issue #103 
@Spandan-Bhattacharya 
i have Improved the design of the 6x6 sudoku solver. i have made it on the same theme as of 4x4 sudoku solver as you have asked.
Screenshot :-
> Improved design of the 6x6 sudoku solver.

- .vscode/settings.json
- css_files/sudoku_solver4.css
- css_files/sudoku_solver6.css
- css_files/sudoku_solver9.css
- javascript/sudoku_solver4.js
- javascript/sudoku_solver6.js
- javascript/sudoku_solver9.js
Different color to the user input cells of sudoku solvers Issue No = **#132**
> Different color to the user input cells of sudoku solvers

- css_files/searchstyle.css
- css_files/styles.css
- index.html
- javascript/autocomplete.js
Enhanced the Search Box to match the theme of the website and also made some major bug fixes in the navbar.
- The Changes made are Responsive for smaller screens as well.
- Closes #133 
I have done Alpha, Beta & Unit Testing
> [ISSUE - 133] Enhance Search Box in the Navbar

- .vscode/settings.json
- javascript/sudoku_solver4.js
- javascript/sudoku_solver6.js
- javascript/sudoku_solver9.js
> fixing up/down arrows and adding checks

- css_files/styles.css
- index.html
suggestion section created for users to suggest their favorite puzzles to add to the website for better interaction
> suggestion section

- css_files/contributors.css
- html_files/about.html
- html_files/contact.html
- html_files/contributors.html
- index.html
- javascript/contributors.js
issue #147 
i have added the contributor page that will get updated everytime a new contribution is merged.
> Added Contributor Page

- css_files/number_solver.css
- html_files/numbersolver.html
- index.html
- javascript/number_solver.js
Title : New solver addition.
Issue : #142
> Added Number Solver

- css_files/number_solver.css
- html_files/numbersolver.html
added back home button in number solver 
solved #168
> added back home button

- css_files/wordsolver.css
- html_files/wordsolver.html
- index.html
- javascript/wordsolver.js
Closes #169 
Created New Solver addition: Word Unjumbler
- The word Unjumbler solved the issue of jumbled words.
Tested on my local system and it works fine.
https://github.com/Spandan-Bhattacharya/Solve_it/assets/148339919/76c303e3-0e6d-4957-889d-13eed168c288
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor
> Word Unjumbler

- css_files/toh.css
- html_files/toh.html
- index.html
- javascript/toh.js
- javascript/toh/game.js
A Tower of Hanoi Solver with visual representation.
issue no :160
> added tower of hanoi solution

- css_files/about.css
- html_files/about.html
Made the About Us Page Completely Responsive. Also added a hamburger for mobile devices. Issue no = **#159**
> Made About Us Page Responsive

- html_files/numbersolver.html
- javascript/number_solver.js
Title: Add reset button to Number solver.
Issue : #165
> Reset Button Added

- css_files/contributors.css
- css_files/styles.css
- javascript/contributors.js
changed the color and link added to the name also in the contributors page. please check this jwoc 2024
> required changed done on hover effect of contributors page

- css_files/styles.css
- index.html
#157 Created a loading page of the website please review my pull request.
> Created a loading page

- javascript/sudoku_solver4.js
- javascript/sudoku_solver6.js
- javascript/sudoku_solver9.js
This pull request addresses and resolves Issue #166, which was related to the reset color problem. The changes implemented ensure that all three sudoku functionalities now operate seamlessly, and the color resetting issue has been successfully resolved. The adjustments made guarantee a smooth user experience with no lingering color-related challenges.
> reset color problem fixed

- css_files/_8_puzzle.css
- html_files/_8_puzzle.html
- index.html
- javascript/_8_puzzle.js
- Title : New Solver Addition : 8 Puzzle
- issue : #179 
- Important Details: I implemented the A* algorithm to solve this puzzle. Add a maximum Iterations limit of 10000 to prevent the page stop responding but that is why this solution can't solve all possible combinations.
https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/368927ac-8b40-4f6e-89f7-bc4cf20f16b2
> 8 Puzzle Solver Added

- css_files/queens.css
- html_files/queens.html
- index.html
- javascript/queens.js
I did the changes you asked for, but i wasn't able to provide a traditional chessboard look if you could merge my PR without this particular change then i would be utterly grateful as i tried a lot but was not able to give it a traditional chess board look .
Also now if you would click on a placed queen then it would get deleted, which allows you to make placement changes.
https://github.com/Spandan-Bhattacharya/Solve_it/assets/140010647/5147bc03-03fa-4657-8098-9b3a77759d3d
> Added N-Queen Problem Solver

- css_files/number_solver.css
- html_files/numbersolver.html
I changed the background color of the Number Solver to the background color of home screen and also changed the colors of different contents according to the home screen color design.
> Changed the color palette of Number Solver to theme colors

- index.html
- javascript/script.js
#198 closes
Search bar is been functional now
https://github.com/Spandan-Bhattacharya/Solve_it/assets/148339919/0939546b-1e11-4e19-af41-faa88b0c9363
Tested on my local system and it works fine
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor
> Make the Search bar functional. #198

- css_files/contributors.css
- css_files/newContact.css
- html_files/contributors.html
- html_files/newContact.html
Made the Navbar for pages responsive with Hamburger.
Issue No = #161
> Made the Navbar for pages responsive with Hamburger

- javascript/wordsolver.js
This pr resolves issue #197.
For the word **Ahead**:
Before:
After:
> Resolving word unjumbler bug

- css_files/toh.css
- html_files/toh.html
- javascript/toh.js
- javascript/toh/game.js
> Enhance the UI of the Tower of Hanoi solver. #191

- css_files/styles.css
- html_files/about.html
- html_files/contributors.html
- html_files/faq.html
- html_files/newContact.html
- index.html
- javascript/animation.js
- javascript/faq.js
Added Animations to the Website in each and every page.
Issue no = **#206**
> Add Animations to Website

- css_files/styles.css
- html_files/about.html
- html_files/contributors.html
- html_files/faq.html
- html_files/newContact.html
- index.html
- javascript/animation.js
- javascript/faq.js
#199 placed the bubbles uniformly and changed the colour of it please check my pull request.
> #199 fixed the issue

- css_files/wordsolver.css
- html_files/wordsolver.html
- javascript/wordsolver.js
Added `back-to-home` button in the word unjumbler.
> Added back-to-home button

- css_files/faq.css
- html_files/faq.html
#213 I had changed the navbar and footer style of the faq page , please check my pull request.
> Fixed the faq page

- css_files/sudoku_solver8.css
- html_files/sudoku_solver_8x8.html
- javascript/sudoku_solver8.js
Title : Improve the 8x8 solver.
Issue : #217
Changes : 
1. Font changed as 4x4 solver.
2. Solve animation added as 9x9 solver.
3. Fixed reset coloring issue.
Improved version : 
[screen-capture.webm](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/65697fe5-ada8-4832-8ea3-1117c5718aa8)
> Improved 8x8 suduku solver

- css_files/sudoku_solver9.css
- html_files/sudoku_solver_9x9.html
- javascript/sudoku_solver9.js
Title : Improve the 9x9 solver.
Issue : #218 
Changes :
1. Font changed as 4x4 solver.
2. make it responsive for all devices.
3. Fixed reset coloring issue.
Video : 
[screen-capture (1).webm](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/994da30a-f123-47c3-8561-78fd57c400c9)
> Improved 9x9 Solver UI

- css_files/queens.css
- html_files/queens.html
- javascript/queens.js
Title : Improve N queen solver
Issue : #224 
Changes : 
1. Added the feature to generate solutions for all n values from 1 to 10.
2. created  checker board pattern.(alternate dark and light squares)
3. Added a reset button
4. Added a back to home button.
Video : 
[screen-capture (2).webm](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/bbde3a81-a611-453e-b0af-89adfca0eedd)
> Improved N Queen Solver

- index.html
- javascript/autocomplete.js
Title : Improve Search Bar
Issue : #211
Currently : 
1. drop down showing correct results.
2. When the items in the drop down are clicked, the user is redirected to that solver.
3. When the exit(x) sign is pressed in the search bar, all the solvers are showing.
Video : 
[screen-capture.webm](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/58385893-a17f-4a35-907c-c4a05aaa72d8)
> Improved Search Bar

- css_files/toh.css
- html_files/toh.html
Improved Tower Of Hanoi : 
1. Make the solver responsive.
2. Rename the new game button to reset button and shift its position to beside the solve button.
3. Make the solver match the theme of the the other solvers.
Issue No = #221
> Improved Tower Of Hanoi

- css_files/queens.css
- html_files/queens.html
- javascript/queens.js
Title : N Queens Solver UI update
Issue : #239 
Changes : 
1. Responsive to all devices.
2. Match the colors & styles with the other solvers.
3. Match the fonts with the other solvers.
4. Board size changes with the selection of the size in dropdown.
Video : 
[screen-capture (3).webm](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/113f2679-db70-431e-9882-b442bb4d37e3)
> Improved UI of N Queens Solver

- css_files/toh.css
Solved Bug in tower of Hanoi :
1. The scrollbar in the textarea moves out of box for larger inputs. Fixed this issue.
2. Redesign the buttons as they are not designed
Issue No = #241
> Solved Bug in tower of Hanoi

- css_files/styles.css
- index.html
Changed In Home Page : 
1. In home page, in place of the 9 cards for each solver, we will have only 2 cards: 1) PLAY, 2) SOLVE
2. once solve is clicked, then the 9 solvers are shown in the same page like right now.
3. once play is clicked, then the games(yet to be added) cards will be shown.
Issue No = #244
> Changed In Home Page

- css_files/queens.css
- javascript/queens.js
Title : User Input in N Queen Solver
Issue : #243 
Video : 
[screen-capture (4).webm](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/4d8dee9f-3e38-4230-9631-6c7c30da78f9)
> Added User Input in N Queen Solver

- css_files/checkers_game.css
- html_files/checkers_game.html
- index.html
- javascript/checkers_game.js
Title : Add Checkers Game
Issue : #258 
Screenshots :
> Added Checker Game

- css_files/_8_Puzzle_game.css
- html_files/_8_Puzzle_game.html
- index.html
- javascript/_8_Puzzle_game.js
Title : Add 8 Puzzle Game
Issue : #260 
Screenshots :
> Added 8 Puzzle Game

- Word Scramble/index.html
- Word Scramble/script.js
- Word Scramble/style.css
- Word Scramble/word.js
- index.html
Added Word Scramble game !
Issue No = #271
> Added Word Scramble game

- CrossWord/app.js
- CrossWord/index.html
- CrossWord/style.css
- index.html
Title : Add Crossword Game 
issue : #268
Screenshots :
> Added Crossword Game

- Snake Game/index.html
- Snake Game/script.js
- Snake Game/style.css
- index.html
Added Snake Game !
Issue No = #275
> Added Snake Game

- 2048/app.js
- 2048/index.html
- 2048/style.css
- index.html
Title :  Add 2048 Game 
issue: #278 
Screenshots :
> Added 2048 Game

- Tetris/app.js
- Tetris/index.html
- Tetris/style.css
- index.html
Title : Add Tetris Game 
issue : #282
Screenshots :
> Added Tetris Game

- Word/index.html
- Word/script.js
- Word/style.css
- Word/word.js
- index.html
new game Word Guessing Game #284
issue #284 
close #284
> new game Word Guessing Game #284

- Block-Buster/index.html
- Block-Buster/script.js
- Block-Buster/styles.css
- index.html
Add new game block buster #295
issue #295 
close #295
> Add new game block buster #295

- Sorting Visualizer/index.html
- Sorting Visualizer/style.css
- css_files/_8_puzzle.css
- css_files/number_solver.css
- css_files/queens.css
- css_files/sudoku_solver4.css
- css_files/sudoku_solver6.css
- css_files/sudoku_solver8.css
- css_files/sudoku_solver9.css
- css_files/toh.css
- css_files/wordsolver.css
- html_files/_8_puzzle.html
- html_files/numbersolver.html
- html_files/queens.html
- html_files/sudoku_solver_4x4.html
- html_files/sudoku_solver_6x6.html
- html_files/sudoku_solver_8x8.html
- html_files/sudoku_solver_9x9.html
- html_files/toh.html
- html_files/wordsolver.html
I had added navbar and footer to all the pages  of puzzles , please check my pull request.
> Added navbar and footer to all the puzzle pages

- css_files/newContact.css
- html_files/newContact.html
- index.html
- javascript/autocomplete.js
Title : Improve Search function & UI 
issue : #300
changes : 
- Improved Search bar 
- Improved UI of contact page
> Improved Search function and UI

- Bingo Game/app.js
- Bingo Game/index.html
- Bingo Game/style.css
- index.html
- javascript/autocomplete.js
Title : Add Bingo Game 
Issue : #303
Screenshots :
> Added Bingo Game

- Block-Buster/index.html
- Block-Buster/styles.css
- HangMan Game/index.html
- HangMan Game/style.css
- Memory Card game/index.html
- Memory Card game/style.css
- Ping_Pong/index.html
- Ping_Pong/style.css
- Rock Paper Scissor/index.html
- Rock Paper Scissor/style.css
- Simon Game/index.html
- Simon Game/styles.css
- Snake Game/index.html
- Snake Game/style.css
- Sorting Visualizer/index.html
- Sorting Visualizer/style.css
- Tic-Tac-Toe/index.html
- Tic-Tac-Toe/style.css
- UNO/css/style.css
- UNO/index.html
- Word Scramble/index.html
- Word Scramble/style.css
- Word/index.html
- Word/style.css
> add back to home button

- css_files/styles.css
- index.html
Title : Make the home page responsive. 
Issue : #323
> Improved Responsiveness of home page
